# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: 'API Documentation'
            description: 'Documentation de l''API'
            version: '1.0.0'
